# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.IntegerField()),
                ('easting', models.IntegerField()),
                ('northing', models.IntegerField()),
                ('link_length', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EstimationMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Junction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalAuthority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RoadCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('description', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('estimated', models.BooleanField()),
                ('count_cycles', models.IntegerField()),
                ('count_motorcycles', models.IntegerField()),
                ('count_cars', models.IntegerField()),
                ('count_buses', models.IntegerField()),
                ('count_lightgoods', models.IntegerField()),
                ('count_hgv_2ax_rigid', models.IntegerField()),
                ('count_hgv_3ax_rigid', models.IntegerField()),
                ('count_hgv_45ax_rigid', models.IntegerField()),
                ('count_hgv_34ax_artic', models.IntegerField()),
                ('count_hgv_5ax_artic', models.IntegerField()),
                ('count_hgv_6plus_artic', models.IntegerField()),
                ('count_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.CountPoint')),
                ('estimation_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.EstimationMethod')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('local_authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.LocalAuthority')),
            ],
        ),
        migrations.AddField(
            model_name='road',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roads', to='api_app.RoadCategory'),
        ),
        migrations.AddField(
            model_name='localauthority',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_authorities', to='api_app.Region'),
        ),
        migrations.AddField(
            model_name='countpoint',
            name='end_junction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='road_ends', to='api_app.Junction'),
        ),
        migrations.AddField(
            model_name='countpoint',
            name='road',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.Road'),
        ),
        migrations.AddField(
            model_name='countpoint',
            name='start_junction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='road_starts', to='api_app.Junction'),
        ),
        migrations.AddField(
            model_name='countpoint',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.Ward'),
        ),
        migrations.AlterUniqueTogether(
            name='ward',
            unique_together=set([('name', 'local_authority')]),
        ),
        migrations.AlterUniqueTogether(
            name='trafficcount',
            unique_together=set([('count_point', 'year')]),
        ),
        migrations.AlterUniqueTogether(
            name='road',
            unique_together=set([('name', 'category')]),
        ),
        migrations.AlterUniqueTogether(
            name='localauthority',
            unique_together=set([('name', 'region')]),
        ),
        migrations.AlterUniqueTogether(
            name='countpoint',
            unique_together=set([('reference', 'road', 'easting', 'northing', 'start_junction', 'end_junction')]),
        ),
    ]
