# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.IntegerField()),
                ('easting', models.IntegerField()),
                ('northing', models.IntegerField()),
                ('link_length', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EstimationMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Junction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalAuthority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RoadCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('description', models.TextField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='road',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roads', to='api_app.RoadCategory'),
        ),
        migrations.AddField(
            model_name='localauthority',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_authorities', to='api_app.Region'),
        ),
        migrations.AddField(
            model_name='countpoint',
            name='end_junction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='road_ends', to='api_app.Junction'),
        ),
        migrations.AddField(
            model_name='countpoint',
            name='local_authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.LocalAuthority'),
        ),
        migrations.AddField(
            model_name='countpoint',
            name='road',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.Road'),
        ),
        migrations.AddField(
            model_name='countpoint',
            name='start_junction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='road_starts', to='api_app.Junction'),
        ),
        migrations.AlterUniqueTogether(
            name='road',
            unique_together=set([('name', 'category')]),
        ),
        migrations.AlterUniqueTogether(
            name='localauthority',
            unique_together=set([('name', 'region')]),
        ),
        migrations.AlterUniqueTogether(
            name='countpoint',
            unique_together=set([('reference', 'road', 'easting', 'northing', 'start_junction', 'end_junction')]),
        ),
    ]
