# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('local_authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.LocalAuthority')),
            ],
        ),
    ]
