# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='ward',
            unique_together=set([('name', 'local_authority')]),
        ),
    ]
