# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalAuthority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='localauthority',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_authorities', to='api_app.Region'),
        ),
        migrations.AlterUniqueTogether(
            name='localauthority',
            unique_together=set([('name', 'region')]),
        ),
    ]
